/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hibernate.facturation2.view;

import java.awt.Dimension;

/**
 *
 * @author youyou
 */
public class FacturationApp2UI extends javax.swing.JFrame {

    /**
     * Creates new form FacturationApp2UI
     */
    public FacturationApp2UI() {
        initComponents();
        this.panelsSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeft = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMenuProduit = new javax.swing.JPanel();
        panelMenuClient = new javax.swing.JPanel();
        panelMenuFacture = new javax.swing.JPanel();
        panelMenuVente = new javax.swing.JPanel();
        panelContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(750, 350));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        panelLeft.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelLeft.setLayout(new java.awt.CardLayout());

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelLeft.add(panelMenu, "card2");

        javax.swing.GroupLayout panelMenuProduitLayout = new javax.swing.GroupLayout(panelMenuProduit);
        panelMenuProduit.setLayout(panelMenuProduitLayout);
        panelMenuProduitLayout.setHorizontalGroup(
            panelMenuProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        panelMenuProduitLayout.setVerticalGroup(
            panelMenuProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        panelLeft.add(panelMenuProduit, "card3");

        javax.swing.GroupLayout panelMenuClientLayout = new javax.swing.GroupLayout(panelMenuClient);
        panelMenuClient.setLayout(panelMenuClientLayout);
        panelMenuClientLayout.setHorizontalGroup(
            panelMenuClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        panelMenuClientLayout.setVerticalGroup(
            panelMenuClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        panelLeft.add(panelMenuClient, "card4");

        javax.swing.GroupLayout panelMenuFactureLayout = new javax.swing.GroupLayout(panelMenuFacture);
        panelMenuFacture.setLayout(panelMenuFactureLayout);
        panelMenuFactureLayout.setHorizontalGroup(
            panelMenuFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        panelMenuFactureLayout.setVerticalGroup(
            panelMenuFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        panelLeft.add(panelMenuFacture, "card5");

        javax.swing.GroupLayout panelMenuVenteLayout = new javax.swing.GroupLayout(panelMenuVente);
        panelMenuVente.setLayout(panelMenuVenteLayout);
        panelMenuVenteLayout.setHorizontalGroup(
            panelMenuVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        panelMenuVenteLayout.setVerticalGroup(
            panelMenuVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        panelLeft.add(panelMenuVente, "card6");

        panelContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel3))
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel2)))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(200, 200, 200)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        this.panelsSize();
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturationApp2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturationApp2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturationApp2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturationApp2UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturationApp2UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMenuClient;
    private javax.swing.JPanel panelMenuFacture;
    private javax.swing.JPanel panelMenuProduit;
    private javax.swing.JPanel panelMenuVente;
    // End of variables declaration//GEN-END:variables
        
    private void panelsSize() {
        final double LEFTPANEL = 0.25;
        final int MAX_LEFTPANEL = 280;
        final int MIN_LEFTPANEL = 85;
                
        panelMenu.setSize(panelLeft.getWidth()-5, panelLeft.getHeight()-5);
        panelMenuClient.setSize(panelLeft.getWidth()-5, panelLeft.getHeight()-5);
        panelMenuProduit.setSize(panelLeft.getWidth()-5, panelLeft.getHeight()-5);
        panelMenuFacture.setSize(panelLeft.getWidth()-5, panelLeft.getHeight()-5);
        panelMenuVente.setSize(panelLeft.getWidth()-5, panelLeft.getHeight()-5);
        
        if((int)(this.getWidth()*LEFTPANEL) < MIN_LEFTPANEL)
            panelLeft.setSize(MIN_LEFTPANEL, this.getHeight()-50);
            
        else if((int)(this.getWidth()*LEFTPANEL) > MAX_LEFTPANEL)
            panelLeft.setSize(MAX_LEFTPANEL, this.getHeight()-50);
        else
            panelLeft.setSize((int)(this.getWidth()*LEFTPANEL), this.getHeight()-50);
        
        /*panelLeft.setSize((int)(this.getWidth()*LEFTPANEL), this.getHeight()-80);
        panelLeft.setMaximumSize(new Dimension(MAX_LEFTPANEL, this.getHeight()-80));
        panelLeft.setMinimumSize(new Dimension(MIN_LEFTPANEL, this.getHeight()-80));*/
        panelContent.setSize(this.getWidth()-panelLeft.getWidth()-10, this.getHeight()-50);
        
        jLabel1.setText("H : "+panelLeft.getHeight()+", W :"+panelLeft.getWidth());
        jLabel2.setText("H : "+panelContent.getHeight()+", W :"+panelContent.getWidth());
        jLabel3.setText("H : "+this.getHeight()+", W :"+this.getWidth());
        
        //jPanel1.setMaximumSize(new Dimension((int)(this.getWidth()*0.25), this.getHeight()-20));
    }
    
    public javax.swing.JPanel getPanel() {
        return this.panelLeft;
    }
}
