/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hibernate.facturation2.view;

/**
 *
 * @author youyou
 */
public class PanelMenuClient extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuClient
     */
    public PanelMenuClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewClient = new javax.swing.JButton();
        btnFindClient = new javax.swing.JButton();
        btnListClient = new javax.swing.JButton();
        btnBackMainMenu = new javax.swing.JButton();

        btnNewClient.setText("Nouveau Client");

        btnFindClient.setText("Rechercher Client");

        btnListClient.setText("Liste Clients");

        btnBackMainMenu.setText("Retour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnFindClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnBackMainMenu))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackMainMenu)
                .addGap(18, 18, 18)
                .addComponent(btnNewClient)
                .addGap(18, 18, 18)
                .addComponent(btnFindClient)
                .addGap(18, 18, 18)
                .addComponent(btnListClient)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackMainMenu;
    private javax.swing.JButton btnFindClient;
    private javax.swing.JButton btnListClient;
    private javax.swing.JButton btnNewClient;
    // End of variables declaration//GEN-END:variables
}
