/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hibernate.facturation2.view;

/**
 *
 * @author youyou
 */
public class PanelMenuFacture extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuFacture
     */
    public PanelMenuFacture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewFacture = new javax.swing.JButton();
        btnFindFacture = new javax.swing.JButton();
        btnListFacture = new javax.swing.JButton();
        btnBackMainMenu = new javax.swing.JButton();

        btnNewFacture.setText("Nouvelle Facture");

        btnFindFacture.setText("Rechercher Facture");

        btnListFacture.setText("Liste Factures");

        btnBackMainMenu.setText("Retour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnFindFacture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListFacture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewFacture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnBackMainMenu))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackMainMenu)
                .addGap(18, 18, 18)
                .addComponent(btnNewFacture)
                .addGap(18, 18, 18)
                .addComponent(btnFindFacture)
                .addGap(18, 18, 18)
                .addComponent(btnListFacture)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackMainMenu;
    private javax.swing.JButton btnFindFacture;
    private javax.swing.JButton btnListFacture;
    private javax.swing.JButton btnNewFacture;
    // End of variables declaration//GEN-END:variables
}
