/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hibernate.facturation2.view;

/**
 *
 * @author youyou
 */
public class PanelMenuProduit extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuProduit
     */
    public PanelMenuProduit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewProduit = new javax.swing.JButton();
        btnFindProduit = new javax.swing.JButton();
        btnListProduit = new javax.swing.JButton();
        btnBackMainMenu = new javax.swing.JButton();

        btnNewProduit.setText("Nouveau Produit");

        btnFindProduit.setText("Rechercher Produit");

        btnListProduit.setText("Liste Produits");

        btnBackMainMenu.setText("Retour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnFindProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnBackMainMenu))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackMainMenu)
                .addGap(18, 18, 18)
                .addComponent(btnNewProduit)
                .addGap(18, 18, 18)
                .addComponent(btnFindProduit)
                .addGap(18, 18, 18)
                .addComponent(btnListProduit)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackMainMenu;
    private javax.swing.JButton btnFindProduit;
    private javax.swing.JButton btnListProduit;
    private javax.swing.JButton btnNewProduit;
    // End of variables declaration//GEN-END:variables
}
