package com.hibernate.facturation2.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.sql.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

@Entity
public class Vente implements Serializable {

    @Column(nullable = false)
    @Basic
    private long idProduit;

    @OneToOne(fetch = FetchType.LAZY, targetEntity = Produit.class)
    private Produit produit;

    @Basic
    private boolean appliqueTva;

    @Column(nullable = false)
    @Basic
    private Date dateVente;

    @Column(unique = true, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idVente;

    @Column(nullable = false)
    @Basic
    private long idFacture;

    @Basic
    private long quantite;

    public Vente() {

    }

    public long getIdProduit() {
        return this.idProduit;
    }

    public void setIdProduit(long idProduit) {
        this.idProduit = idProduit;
    }

    public Produit getProduit() {
        return this.produit;
    }

    public void setProduit(Produit produit) {
        this.produit = produit;
    }

    public boolean isAppliqueTva() {
        return this.appliqueTva;
    }

    public void setAppliqueTva(boolean appliqueTva) {
        this.appliqueTva = appliqueTva;
    }

    public Date getDateVente() {
        return this.dateVente;
    }

    public void setDateVente(Date dateVente) {
        this.dateVente = dateVente;
    }

    public Long getIdVente() {
        return this.idVente;
    }

    public void setIdVente(Long idVente) {
        this.idVente = idVente;
    }

    public long getIdFacture() {
        return this.idFacture;
    }

    public void setIdFacture(long idFacture) {
        this.idFacture = idFacture;
    }

    public long getQuantite() {
        return this.quantite;
    }

    public void setQuantite(long quantite) {
        this.quantite = quantite;
    }
}
