package com.hibernate.facturation2.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

@Entity
public class Client implements Serializable {

    @Column(length = 1024)
    @Basic
    private String note;

    @Column(unique = true, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idClient;

    @Column(length = 120)
    @Basic
    private String emailClient;

    @OneToMany(fetch = FetchType.LAZY, targetEntity = Facture.class, mappedBy = "client")
    private List<Facture> factures;

    @Embedded
    private Adresse adresse1;

    @Column(nullable = false)
    @Basic
    private String nomClient;

    @Column(length = 20)
    @Basic
    private String telphoneClient;

    public Client() {

    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public Long getIdClient() {
        return this.idClient;
    }

    public void setIdClient(Long idClient) {
        this.idClient = idClient;
    }

    public String getEmailClient() {
        return this.emailClient;
    }

    public void setEmailClient(String emailClient) {
        this.emailClient = emailClient;
    }

    public List<Facture> getFactures() {
        return this.factures;
    }

    public void setFactures(List<Facture> factures) {
        this.factures = factures;
    }

    public Adresse getAdresse1() {
        return this.adresse1;
    }

    public void setAdresse1(Adresse adresse1) {
        this.adresse1 = adresse1;
    }

    public String getNomClient() {
        return this.nomClient;
    }

    public void setNomClient(String nomClient) {
        this.nomClient = nomClient;
    }

    public String getTelphoneClient() {
        return this.telphoneClient;
    }

    public void setTelphoneClient(String telphoneClient) {
        this.telphoneClient = telphoneClient;
    }
}
