package com.hibernate.facturation2.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

@Entity
public class Facture implements Serializable {

    @Basic
    private long idClient;

    @Basic
    private Date datePaiement;

    @Column(nullable = false)
    @Basic
    private Date dateFacture;

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = Client.class)
    //@JoinColumn(columnDefinition = "idClient", name = "clientToFacture", referencedColumnName = "idClient", table = "Client")
    private Client client;

    @Column(unique = true, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idFacture;

    @Column(nullable = false)
    @Basic
    private boolean payer;

    @OneToMany(fetch = FetchType.LAZY, targetEntity = Vente.class)
    private List<Vente> ventes;

    public Facture() {

    }

    public long getIdClient() {
        return this.idClient;
    }

    public void setIdClient(long idClient) {
        this.idClient = idClient;
    }

    public Date getDatePaiement() {
        return this.datePaiement;
    }

    public void setDatePaiement(Date datePaiement) {
        this.datePaiement = datePaiement;
    }

    public Date getDateFacture() {
        return this.dateFacture;
    }

    public void setDateFacture(Date dateFacture) {
        this.dateFacture = dateFacture;
    }

    public Client getClient() {
        return this.client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public Long getIdFacture() {
        return this.idFacture;
    }

    public void setIdFacture(Long idFacture) {
        this.idFacture = idFacture;
    }

    public boolean isPayer() {
        return this.payer;
    }

    public void setPayer(boolean payer) {
        this.payer = payer;
    }

    public List<Vente> getVentes() {
        return this.ventes;
    }

    public void setVentes(List<Vente> ventes) {
        this.ventes = ventes;
    }
}
