package com.hibernate.facturation2.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Produit implements Serializable {

    @Basic
    private Double tvaProduit;

    @Column(unique = true, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idProduit;

    @Column(length = 1024)
    @Basic
    private String description;

    @Column(nullable = false, length = 120)
    @Basic
    private String nomProduit;

    @Basic
    private Double prixProduit;

    public Produit() {

    }

    public Double getTvaProduit() {
        return this.tvaProduit;
    }

    public void setTvaProduit(Double tvaProduit) {
        this.tvaProduit = tvaProduit;
    }

    public Long getIdProduit() {
        return this.idProduit;
    }

    public void setIdProduit(Long idProduit) {
        this.idProduit = idProduit;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getNomProduit() {
        return this.nomProduit;
    }

    public void setNomProduit(String nomProduit) {
        this.nomProduit = nomProduit;
    }

    public Double getPrixProduit() {
        return this.prixProduit;
    }

    public void setPrixProduit(Double prixProduit) {
        this.prixProduit = prixProduit;
    }
}
